# Generated by Django 5.1.7 on 2025-11-07 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv_data', '0019_alter_agv_journey_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique identifier, e.g., 'CA_01' or 'LSA_01_02'", max_length=100, unique=True)),
                ('resource_type', models.CharField(choices=[('CA', 'Crossroad Agent'), ('LSA', 'Logical Segment Agent')], help_text='Resource type (CA or LSA)', max_length=3)),
            ],
            options={
                'verbose_name': 'Resource Agent',
                'verbose_name_plural': 'Resource Agents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agv_id', models.BigIntegerField(db_index=True, help_text='AGV making the reservation')),
                ('start_time', models.DateTimeField(help_text='Start time of resource occupation')),
                ('end_time', models.DateTimeField(help_text='End time of resource release')),
                ('resource', models.ForeignKey(help_text='Reserved resource (CA/LSA)', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='agv_data.resourceagent')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['resource', 'start_time'], name='agv_data_bo_resourc_e3d491_idx'), models.Index(fields=['resource', 'end_time'], name='agv_data_bo_resourc_a3b5a3_idx')],
            },
        ),
    ]
