# Generated by Django 5.1.7 on 2025-11-28 11:31

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv_data', '0021_extend_resourceagent_for_map'),
        ('order_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agv',
            name='adjacent_common_nodes',
        ),
        migrations.RemoveField(
            model_name='agv',
            name='backup_nodes',
        ),
        migrations.RemoveField(
            model_name='agv',
            name='common_nodes',
        ),
        migrations.RemoveField(
            model_name='agv',
            name='deadlock_partner_agv_id',
        ),
        migrations.RemoveField(
            model_name='agv',
            name='inbound_path',
        ),
        migrations.RemoveField(
            model_name='agv',
            name='initial_path',
        ),
        migrations.RemoveField(
            model_name='agv',
            name='outbound_path',
        ),
        migrations.RemoveField(
            model_name='agv',
            name='spare_flag',
        ),
        migrations.RemoveField(
            model_name='agv',
            name='waiting_for_deadlock_resolution',
        ),
        migrations.AlterField(
            model_name='agv',
            name='active_order',
            field=models.OneToOneField(blank=True, help_text='Currently executing order (assigned by auction winner selection)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_agv', to='order_data.order'),
        ),
        migrations.AlterField(
            model_name='agv',
            name='current_node',
            field=models.IntegerField(help_text='Current position: node where AGV is located or last left', null=True),
        ),
        migrations.AlterField(
            model_name='agv',
            name='direction_change',
            field=models.IntegerField(choices=[(0, 'Go straight'), (1, 'Turn around'), (2, 'Turn left'), (3, 'Turn right')], help_text='Direction to turn after reaching a node', null=True),
        ),
        migrations.AlterField(
            model_name='agv',
            name='journey_phase',
            field=models.IntegerField(choices=[(0, 'Outbound'), (1, 'Inbound')], default=0, help_text='Journey phase (affects load weight in energy calculation)'),
        ),
        migrations.AlterField(
            model_name='agv',
            name='motion_state',
            field=models.IntegerField(choices=[(0, 'Idle'), (1, 'Moving'), (2, 'Waiting')], default=0, help_text='Current motion state'),
        ),
        migrations.AlterField(
            model_name='agv',
            name='next_node',
            field=models.IntegerField(help_text='Next node to visit', null=True),
        ),
        migrations.AlterField(
            model_name='agv',
            name='previous_node',
            field=models.IntegerField(help_text='Last node visited (for direction calculation)', null=True),
        ),
        migrations.AlterField(
            model_name='agv',
            name='remaining_path',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, help_text='Remaining nodes to visit (used for calculating J1 cost in busy AGVs)', size=None),
        ),
        migrations.AlterField(
            model_name='agv',
            name='reserved_node',
            field=models.IntegerField(help_text='Reserved node (booked via Reservation Table)', null=True),
        ),
        migrations.AlterField(
            model_name='resourceagent',
            name='from_ca',
            field=models.ForeignKey(blank=True, help_text='(LSA only) Starting node of this edge', limit_choices_to=models.Q(('resource_type', 'LSA'), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edges_out', to='agv_data.resourceagent'),
        ),
        migrations.AlterField(
            model_name='resourceagent',
            name='name',
            field=models.CharField(help_text="Unique identifier, e.g., 'CA-01', 'LSA_01_02', 'DEPOT-01', 'STATION-A'", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='resourceagent',
            name='to_ca',
            field=models.ForeignKey(blank=True, help_text='(LSA only) Ending node of this edge', limit_choices_to=models.Q(('resource_type', 'LSA'), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edges_in', to='agv_data.resourceagent'),
        ),
    ]
